// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: observability/v1/observability.proto

package observabilityv1connect

import (
	v1 "OlympusGCP-Observability/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/observability/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ObservabilityServiceName is the fully-qualified name of the ObservabilityService service.
	ObservabilityServiceName = "observability.v1.ObservabilityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ObservabilityServiceWriteLogProcedure is the fully-qualified name of the ObservabilityService's
	// WriteLog RPC.
	ObservabilityServiceWriteLogProcedure = "/observability.v1.ObservabilityService/WriteLog"
	// ObservabilityServiceRecordMetricProcedure is the fully-qualified name of the
	// ObservabilityService's RecordMetric RPC.
	ObservabilityServiceRecordMetricProcedure = "/observability.v1.ObservabilityService/RecordMetric"
	// ObservabilityServiceStartSpanProcedure is the fully-qualified name of the ObservabilityService's
	// StartSpan RPC.
	ObservabilityServiceStartSpanProcedure = "/observability.v1.ObservabilityService/StartSpan"
	// ObservabilityServiceEndSpanProcedure is the fully-qualified name of the ObservabilityService's
	// EndSpan RPC.
	ObservabilityServiceEndSpanProcedure = "/observability.v1.ObservabilityService/EndSpan"
)

// ObservabilityServiceClient is a client for the observability.v1.ObservabilityService service.
type ObservabilityServiceClient interface {
	WriteLog(context.Context, *connect.Request[v1.WriteLogRequest]) (*connect.Response[v1.WriteLogResponse], error)
	RecordMetric(context.Context, *connect.Request[v1.RecordMetricRequest]) (*connect.Response[v1.RecordMetricResponse], error)
	StartSpan(context.Context, *connect.Request[v1.StartSpanRequest]) (*connect.Response[v1.StartSpanResponse], error)
	EndSpan(context.Context, *connect.Request[v1.EndSpanRequest]) (*connect.Response[v1.EndSpanResponse], error)
}

// NewObservabilityServiceClient constructs a client for the observability.v1.ObservabilityService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewObservabilityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ObservabilityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	observabilityServiceMethods := v1.File_observability_v1_observability_proto.Services().ByName("ObservabilityService").Methods()
	return &observabilityServiceClient{
		writeLog: connect.NewClient[v1.WriteLogRequest, v1.WriteLogResponse](
			httpClient,
			baseURL+ObservabilityServiceWriteLogProcedure,
			connect.WithSchema(observabilityServiceMethods.ByName("WriteLog")),
			connect.WithClientOptions(opts...),
		),
		recordMetric: connect.NewClient[v1.RecordMetricRequest, v1.RecordMetricResponse](
			httpClient,
			baseURL+ObservabilityServiceRecordMetricProcedure,
			connect.WithSchema(observabilityServiceMethods.ByName("RecordMetric")),
			connect.WithClientOptions(opts...),
		),
		startSpan: connect.NewClient[v1.StartSpanRequest, v1.StartSpanResponse](
			httpClient,
			baseURL+ObservabilityServiceStartSpanProcedure,
			connect.WithSchema(observabilityServiceMethods.ByName("StartSpan")),
			connect.WithClientOptions(opts...),
		),
		endSpan: connect.NewClient[v1.EndSpanRequest, v1.EndSpanResponse](
			httpClient,
			baseURL+ObservabilityServiceEndSpanProcedure,
			connect.WithSchema(observabilityServiceMethods.ByName("EndSpan")),
			connect.WithClientOptions(opts...),
		),
	}
}

// observabilityServiceClient implements ObservabilityServiceClient.
type observabilityServiceClient struct {
	writeLog     *connect.Client[v1.WriteLogRequest, v1.WriteLogResponse]
	recordMetric *connect.Client[v1.RecordMetricRequest, v1.RecordMetricResponse]
	startSpan    *connect.Client[v1.StartSpanRequest, v1.StartSpanResponse]
	endSpan      *connect.Client[v1.EndSpanRequest, v1.EndSpanResponse]
}

// WriteLog calls observability.v1.ObservabilityService.WriteLog.
func (c *observabilityServiceClient) WriteLog(ctx context.Context, req *connect.Request[v1.WriteLogRequest]) (*connect.Response[v1.WriteLogResponse], error) {
	return c.writeLog.CallUnary(ctx, req)
}

// RecordMetric calls observability.v1.ObservabilityService.RecordMetric.
func (c *observabilityServiceClient) RecordMetric(ctx context.Context, req *connect.Request[v1.RecordMetricRequest]) (*connect.Response[v1.RecordMetricResponse], error) {
	return c.recordMetric.CallUnary(ctx, req)
}

// StartSpan calls observability.v1.ObservabilityService.StartSpan.
func (c *observabilityServiceClient) StartSpan(ctx context.Context, req *connect.Request[v1.StartSpanRequest]) (*connect.Response[v1.StartSpanResponse], error) {
	return c.startSpan.CallUnary(ctx, req)
}

// EndSpan calls observability.v1.ObservabilityService.EndSpan.
func (c *observabilityServiceClient) EndSpan(ctx context.Context, req *connect.Request[v1.EndSpanRequest]) (*connect.Response[v1.EndSpanResponse], error) {
	return c.endSpan.CallUnary(ctx, req)
}

// ObservabilityServiceHandler is an implementation of the observability.v1.ObservabilityService
// service.
type ObservabilityServiceHandler interface {
	WriteLog(context.Context, *connect.Request[v1.WriteLogRequest]) (*connect.Response[v1.WriteLogResponse], error)
	RecordMetric(context.Context, *connect.Request[v1.RecordMetricRequest]) (*connect.Response[v1.RecordMetricResponse], error)
	StartSpan(context.Context, *connect.Request[v1.StartSpanRequest]) (*connect.Response[v1.StartSpanResponse], error)
	EndSpan(context.Context, *connect.Request[v1.EndSpanRequest]) (*connect.Response[v1.EndSpanResponse], error)
}

// NewObservabilityServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewObservabilityServiceHandler(svc ObservabilityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	observabilityServiceMethods := v1.File_observability_v1_observability_proto.Services().ByName("ObservabilityService").Methods()
	observabilityServiceWriteLogHandler := connect.NewUnaryHandler(
		ObservabilityServiceWriteLogProcedure,
		svc.WriteLog,
		connect.WithSchema(observabilityServiceMethods.ByName("WriteLog")),
		connect.WithHandlerOptions(opts...),
	)
	observabilityServiceRecordMetricHandler := connect.NewUnaryHandler(
		ObservabilityServiceRecordMetricProcedure,
		svc.RecordMetric,
		connect.WithSchema(observabilityServiceMethods.ByName("RecordMetric")),
		connect.WithHandlerOptions(opts...),
	)
	observabilityServiceStartSpanHandler := connect.NewUnaryHandler(
		ObservabilityServiceStartSpanProcedure,
		svc.StartSpan,
		connect.WithSchema(observabilityServiceMethods.ByName("StartSpan")),
		connect.WithHandlerOptions(opts...),
	)
	observabilityServiceEndSpanHandler := connect.NewUnaryHandler(
		ObservabilityServiceEndSpanProcedure,
		svc.EndSpan,
		connect.WithSchema(observabilityServiceMethods.ByName("EndSpan")),
		connect.WithHandlerOptions(opts...),
	)
	return "/observability.v1.ObservabilityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ObservabilityServiceWriteLogProcedure:
			observabilityServiceWriteLogHandler.ServeHTTP(w, r)
		case ObservabilityServiceRecordMetricProcedure:
			observabilityServiceRecordMetricHandler.ServeHTTP(w, r)
		case ObservabilityServiceStartSpanProcedure:
			observabilityServiceStartSpanHandler.ServeHTTP(w, r)
		case ObservabilityServiceEndSpanProcedure:
			observabilityServiceEndSpanHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedObservabilityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedObservabilityServiceHandler struct{}

func (UnimplementedObservabilityServiceHandler) WriteLog(context.Context, *connect.Request[v1.WriteLogRequest]) (*connect.Response[v1.WriteLogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("observability.v1.ObservabilityService.WriteLog is not implemented"))
}

func (UnimplementedObservabilityServiceHandler) RecordMetric(context.Context, *connect.Request[v1.RecordMetricRequest]) (*connect.Response[v1.RecordMetricResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("observability.v1.ObservabilityService.RecordMetric is not implemented"))
}

func (UnimplementedObservabilityServiceHandler) StartSpan(context.Context, *connect.Request[v1.StartSpanRequest]) (*connect.Response[v1.StartSpanResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("observability.v1.ObservabilityService.StartSpan is not implemented"))
}

func (UnimplementedObservabilityServiceHandler) EndSpan(context.Context, *connect.Request[v1.EndSpanRequest]) (*connect.Response[v1.EndSpanResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("observability.v1.ObservabilityService.EndSpan is not implemented"))
}
